### ISSUE TITLE
Preconfigured policies is consistently failing on CI for Debian on AMD

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1791]
This is the failing test: 

> Step a "debian" agent is deployed to Fleet with "tar" installer

Happening at master, 8.0 and 7.16, but only on the AMD flavour, the ARM ones pass.

| Branch | CI build | Container logs |
|--------|---------|----------------|
| master | https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/1966 | https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/master/1966/artifact/docker_logs_ubuntu-18.04_amd64_fleet_Preconfigured%20Policies.log |
| 8.0 | https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/8.0/40/pipeline | https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/master/1966/artifact/docker_logs_ubuntu-18.04_amd64_fleet_Preconfigured%20Policies.log |
| 7.16 | https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.16/116| https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-mbp/job/7.16/116/artifact/docker_logs_ubuntu-18.04_amd64_fleet_Preconfigured%20Policies.log |

cc/ @nchaulet @adam-stokes 

### Sample logs

**master**
>[elastic-package-stack_fleet-server_1][docker.elastic.co/beats/elastic-agent-complete:8.1.0-f479a40a-SNAPSHOT][fd4f259bfd877a7408d5f534810b956cf730970dd72d0a1a63a04a416d4a21a6][2021-11-10T05:48:43.859Z] 2021-11-10T05:48:43.858Z	ERROR	fleet/fleet_gateway.go:180	failed to dispatch actions, error: acknowledge 1 actions '[action_id: policy:c6a80bd0-41e9-11ec-85e5-ebeb88d85a6e:1:1, type: POLICY_CHANGE]' for elastic-agent '82d72bbc-a72c-4bb0-a36e-24ac1b5c706e' failed: status code: 400, fleet-server returned an error: BadRequest
[elastic-package-stack_fleet-server_1][docker.elastic.co/beats/elastic-agent-complete:8.1.0-f479a40a-SNAPSHOT][fd4f259bfd877a7408d5f534810b956cf730970dd72d0a1a63a04a416d4a21a6][2021-11-10T05:48:43.859Z] 2021-11-10T05:48:43.859Z	ERROR	status/reporter.go:236	Elastic Agent status changed to: 'error'
[elastic-package-stack_fleet-server_1][docker.elastic.co/beats/elastic-agent-complete:8.1.0-f479a40a-SNAPSHOT][fd4f259bfd877a7408d5f534810b956cf730970dd72d0a1a63a04a416d4a21a6][2021-11-10T05:48:45.232Z] 2021-11-10T05:48:45.232Z	ERROR	fleet/fleet_gateway.go:205	Could not communicate with fleet-server Checking API will retry, error: fail to checkin to fleet-server: Post "http://0.0.0.0:8220/api/fleet/agents/82d72bbc-a72c-4bb0-a36e-24ac1b5c706e/checkin?": dial tcp 0.0.0.0:8220: connect: connection refused

**8.0**
>[elastic-package-stack_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-be754c25-SNAPSHOT][4ccc9c6bced032f1c7a9a004ba210f50627947265297b516c1bde71a9b486087][2021-11-10T06:08:19.191Z] [2021-11-10T06:08:19.190+00:00][WARN ][plugins.monitoring.monitoring.kibana-monitoring] ConnectionError: connect ECONNREFUSED 172.18.0.3:9200
[elastic-package-stack_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-be754c25-SNAPSHOT][4ccc9c6bced032f1c7a9a004ba210f50627947265297b516c1bde71a9b486087][2021-11-10T06:08:19.191Z]     at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:504:31)
[elastic-package-stack_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-be754c25-SNAPSHOT][4ccc9c6bced032f1c7a9a004ba210f50627947265297b516c1bde71a9b486087][2021-11-10T06:08:19.191Z]     at runMicrotasks (<anonymous>)
[elastic-package-stack_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-be754c25-SNAPSHOT][4ccc9c6bced032f1c7a9a004ba210f50627947265297b516c1bde71a9b486087][2021-11-10T06:08:19.191Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[elastic-package-stack_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-be754c25-SNAPSHOT][4ccc9c6bced032f1c7a9a004ba210f50627947265297b516c1bde71a9b486087][2021-11-10T06:08:19.191Z]     at Monitoring.bulk (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/monitoring.js:53:16)
[elastic-package-stack_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-be754c25-SNAPSHOT][4ccc9c6bced032f1c7a9a004ba210f50627947265297b516c1bde71a9b486087][2021-11-10T06:08:19.191Z]     at sendBulkPayload (/usr/share/kibana/x-pack/plugins/monitoring/server/kibana_monitoring/lib/send_bulk_payload.js:24:7)
[elastic-package-stack_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-be754c25-SNAPSHOT][4ccc9c6bced032f1c7a9a004ba210f50627947265297b516c1bde71a9b486087][2021-11-10T06:08:19.191Z]     at BulkUploader._onPayload (/usr/share/kibana/x-pack/plugins/monitoring/server/kibana_monitoring/bulk_uploader.js:188:12)
[elastic-package-stack_kibana_1][docker.elastic.co/kibana/kibana:8.0.0-be754c25-SNAPSHOT][4ccc9c6bced032f1c7a9a004ba210f50627947265297b516c1bde71a9b486087][2021-11-10T06:08:19.191Z]     at BulkUploader._fetchAndUpload (/usr/share/kibana/x-pack/plugins/monitoring/server/kibana_monitoring/bulk_uploader.js:174:9)

**7.16**
>[elastic-package-stack_fleet-server_1][docker.elastic.co/beats/elastic-agent-complete:7.16.0-SNAPSHOT][bd7f3b3f3bd074348be641fef14dd719c9827d5be0877551f70b801e5339ab6d][2021-11-10T05:41:43.171Z] 2021-11-10T05:41:43.171Z	ERROR	fleet/fleet_gateway.go:180	failed to dispatch actions, error: acknowledge 1 actions '[action_id: policy:cc9cf7e0-41e8-11ec-a775-f1900540b3c4:1:1, type: POLICY_CHANGE]' for elastic-agent '992c1c6d-1321-43ac-a031-2a1fa6c23ac0' failed: status code: 400, fleet-server returned an error: BadRequest
[elastic-package-stack_fleet-server_1][docker.elastic.co/beats/elastic-agent-complete:7.16.0-SNAPSHOT][bd7f3b3f3bd074348be641fef14dd719c9827d5be0877551f70b801e5339ab6d][2021-11-10T05:41:43.171Z] 2021-11-10T05:41:43.171Z	ERROR	status/reporter.go:236	Elastic Agent status changed to: 'error'

**Comment by mdelapenya** [comment]
I think this will be covered in #2648. Closing
