### ISSUE TITLE
[Elastic-agent] Agent configuration is not found for 7.9.x

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#303]
Error:

```
[2020-09-16T08:45:25.282Z] elastic-agent_1     | could not read configuration file /usr/share/elastic-agent/elastic-agent.yml: (assert) string key required when merging into 'map[interface {}]interface {}' accessing config (source:'/usr/share/elastic-agent/elastic-agent.yml')
[2020-09-16T08:45:25.282Z] elastic-agent_1     | Trace:goroutine 1 [running]:
[2020-09-16T08:45:25.282Z] elastic-agent_1     | runtime/debug.Stack(0xd82036, 0xb, 0xc00060d5a0)
[2020-09-16T08:45:25.282Z] elastic-agent_1     | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
[2020-09-16T08:45:25.282Z] elastic-agent_1     | github.com/elastic/go-ucfg.raiseCritical(0xeb3de0, 0xc000099070, 0xc000140000, 0x95, 0x45, 0xd7d709)
[2020-09-16T08:45:25.282Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/error.go:161 +0x66
[2020-09-16T08:45:25.282Z] elastic-agent_1     | github.com/elastic/go-ucfg.raiseKeyInvalidTypeMerge(0xc00027a630, 0xedf200, 0xc65960, 0xedf200, 0xc65960)
[2020-09-16T08:45:25.282Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/error.go:247 +0x18f
[2020-09-16T08:45:25.282Z] elastic-agent_1     | github.com/elastic/go-ucfg.normalizeMapInto(0xc00027a630, 0xc000310240, 0xc65960, 0xc00027a570, 0x15, 0xc00060d848, 0xc65960)
[2020-09-16T08:45:25.282Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/merge.go:310 +0x2e0
[2020-09-16T08:45:25.282Z] elastic-agent_1     | github.com/elastic/go-ucfg.normalizeMap(0xc000310240, 0xc65960, 0xc00027a570, 0x15, 0x0, 0x0, 0x0)
[2020-09-16T08:45:25.282Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/merge.go:295 +0xa8
[2020-09-16T08:45:25.282Z] elastic-agent_1     | github.com/elastic/go-ucfg.normalize(0xc000310240, 0xc65960, 0xc00027a570, 0xc000310240, 0xcac760, 0x1502101)
[2020-09-16T08:45:25.282Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/merge.go:277 +0x2e9
[2020-09-16T08:45:25.282Z] elastic-agent_1     | github.com/elastic/go-ucfg.(*Config).Merge(0xc00027a5a0, 0xc65960, 0xc00027a570, 0xc0000a6440, 0x4, 0x4, 0xdb9d58, 0xc00060d928)
[2020-09-16T08:45:25.282Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/merge.go:79 +0x78
[2020-09-16T08:45:25.282Z] elastic-agent_1     | github.com/elastic/go-ucfg.NewFrom(0xc65960, 0xc00027a570, 0xc0000a6440, 0x4, 0x4, 0x841700, 0x0, 0x0)
[2020-09-16T08:45:25.282Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/ucfg.go:105 +0xa1
[2020-09-16T08:45:25.283Z] elastic-agent_1     | github.com/elastic/go-ucfg/yaml.NewConfig(0xc0002fc000, 0xe, 0x20e, 0xc0000a6440, 0x4, 0x4, 0x3, 0x3, 0xc0002fa000)
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/yaml/yaml.go:35 +0xe3
[2020-09-16T08:45:25.283Z] elastic-agent_1     | github.com/elastic/go-ucfg/yaml.NewConfigWithFile(0xc0002fa000, 0x2a, 0x14ff950, 0x3, 0x3, 0x18, 0xd86d92, 0x11)
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/pkg/mod/github.com/elastic/go-ucfg@v0.8.3/yaml/yaml.go:48 +0x177
[2020-09-16T08:45:25.283Z] elastic-agent_1     | github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/config.LoadYAML(0xc0002fa000, 0x2a, 0x0, 0x0, 0x0, 0xed38981deb46d5d9, 0xc00060dae0, 0x410413)
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/config/config.go:37 +0x6b
[2020-09-16T08:45:25.283Z] elastic-agent_1     | github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/cmd.run(0xc000186180, 0xc00027a180, 0x0, 0x0)
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/cmd/run.go:42 +0x84
[2020-09-16T08:45:25.283Z] elastic-agent_1     | github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/cmd.newRunCommandWithArgs.func1(0xc0000bcc80, 0x152c0b8, 0x0, 0x0)
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/cmd/run.go:32 +0x3c
[2020-09-16T08:45:25.283Z] elastic-agent_1     | github.com/spf13/cobra.(*Command).execute(0xc0000bcc80, 0x152c0b8, 0x0, 0x0, 0xc0000bcc80, 0x152c0b8)
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x29d
[2020-09-16T08:45:25.283Z] elastic-agent_1     | github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bc280, 0x2, 0x2, 0xc00027a180)
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
[2020-09-16T08:45:25.283Z] elastic-agent_1     | github.com/spf13/cobra.(*Command).Execute(...)
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
[2020-09-16T08:45:25.283Z] elastic-agent_1     | main.main()
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 	/go/src/github.com/elastic/beats/x-pack/elastic-agent/main.go:20 +0x138
[2020-09-16T08:45:25.283Z] elastic-agent_1     | 
[2020-09-16T08:45:25.283Z] elastic-agent_1     | v
```

**Comment by mdelapenya** [comment]
Merged, thanks!

![image](https://media.giphy.com/media/D0WOL0ogZIoG4/giphy.gif)
