### ISSUE TITLE
cli: unable to run profile with attached services

### ISSUE THREAD

**Issue by adam-stokes** [elastic/e2e-testing#944]
```
⏚ [adam:~/Projects/e2e-testing/cli] gh-fix-933 11s 130 ± op run profile fleet -s elastic-agent
fleet_elasticsearch_1 is up-to-date
fleet_package-registry_1 is up-to-date
fleet_kibana_1 is up-to-date
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/elastic/e2e-testing/cli/cmd.buildRunProfileCommand.func1(0xc00078a500, 0xc00069df20, 0x0, 0x2)
        /Users/adam/Projects/e2e-testing/cli/cmd/run.go:103 +0x7b5
github.com/spf13/cobra.(*Command).execute(0xc00078a500, 0xc00069dee0, 0x2, 0x2, 0xc00078a500, 0xc00069dee0)
        /Users/adam/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x4ea8120, 0x8, 0x18, 0xc00069de60)
        /Users/adam/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/adam/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/elastic/e2e-testing/cli/cmd.Execute()
        /Users/adam/Projects/e2e-testing/cli/cmd/root.go:24 +0x42
main.main()
        /Users/adam/Projects/e2e-testing/cli/main.go:17 +0x20
```

**Comment by mdelapenya** [comment]
Good catch! This bug is caused because we are not validating user inputs, and the split method is not covered against invalid values

```golang
services := strings.Split(servicesToRun, ",")

for _, srv := range services {
	arr := strings.Split(srv, ":")
	image := arr[0]
	tag := arr[1]
...
```

**Comment by mdelapenya** [comment]
After fixing that, you'll notice that the elastic-agent docker image mounts a volume provided by the e2e side (look for `elasticAgentConfigFile`).
